on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
   
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R packages 
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::rmarkdown
            
      - name: Render qmd files
        run: |
          mkdir build
          quarto render index.qmd --output-dir build
      
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          clean: true
